spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d901taugvqtc7393ijk0-a.singapore-postgres.render.com:5432/consorcio_euk3
spring.datasource.username=consorcio_euk3_user
spring.datasource.password=cclHWKRAu7aO4o224WJELPJLlyiIdmj6
spring.messages.basename=messages
