spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d88hohbeo5us73fu93lg-a.singapore-postgres.render.com:5432/consorcio_ydqd
spring.datasource.username=consorcio_ydqd_user
spring.datasource.password=golkIBRzfRU7nR9ObkVnniajWFDgCyLC

