spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d9uei9ajobas73ee3870-a.singapore-postgres.render.com:5432/consorcio_rc43
spring.datasource.username=consorcio_rc43_user
spring.datasource.password=J9lyCVjZkYrJWMTU1SlheauI0POh74cM
spring.messages.basename=messages
